################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
driver/adc12.obj: ../driver/adc12.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/adc12.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/adc12_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/adc12.pp" --obj_directory="driver" >> "driver/adc12_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/adc12_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/adc12_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/adc12_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/buzzer.obj: ../driver/buzzer.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/buzzer.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/buzzer_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/buzzer.pp" --obj_directory="driver" >> "driver/buzzer_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/buzzer_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/buzzer_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/buzzer_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/display.obj: ../driver/display.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/display.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/display_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/display.pp" --obj_directory="driver" >> "driver/display_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/display_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/display_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/display_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/display1.obj: ../driver/display1.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/display1.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/display1_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/display1.pp" --obj_directory="driver" >> "driver/display1_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/display1_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/display1_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/display1_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/flash.obj: ../driver/flash.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/flash.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/flash_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/flash.pp" --obj_directory="driver" >> "driver/flash_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/flash_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/flash_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/flash_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/pmm.obj: ../driver/pmm.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/pmm.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/pmm_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/pmm.pp" --obj_directory="driver" >> "driver/pmm_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/pmm_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/pmm_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/pmm_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/ports.obj: ../driver/ports.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/ports.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/ports_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/ports.pp" --obj_directory="driver" >> "driver/ports_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/ports_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/ports_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/ports_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/radio.obj: ../driver/radio.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/radio.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/radio_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/radio.pp" --obj_directory="driver" >> "driver/radio_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/radio_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/radio_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/radio_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/rf1a.obj: ../driver/rf1a.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/rf1a.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/rf1a_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/rf1a.pp" --obj_directory="driver" >> "driver/rf1a_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/rf1a_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/rf1a_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/rf1a_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/timer.obj: ../driver/timer.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/timer.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/timer_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/timer.pp" --obj_directory="driver" >> "driver/timer_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/timer_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/timer_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/timer_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/vti_as.obj: ../driver/vti_as.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/vti_as.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/vti_as_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/vti_as.pp" --obj_directory="driver" >> "driver/vti_as_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/vti_as_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/vti_as_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/vti_as_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

driver/vti_ps.obj: ../driver/vti_ps.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/vti_ps.pp" --obj_directory="driver"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "driver/vti_ps_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="driver/vti_ps.pp" --obj_directory="driver" >> "driver/vti_ps_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "driver/vti_ps_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "driver/vti_ps_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"driver/vti_ps_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '


