################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
logic/acceleration.obj: ../logic/acceleration.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/acceleration.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/acceleration_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/acceleration.pp" --obj_directory="logic" >> "logic/acceleration_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/acceleration_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/acceleration_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/acceleration_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/altitude.obj: ../logic/altitude.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/altitude.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/altitude_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/altitude.pp" --obj_directory="logic" >> "logic/altitude_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/altitude_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/altitude_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/altitude_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/battery.obj: ../logic/battery.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/battery.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/battery_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/battery.pp" --obj_directory="logic" >> "logic/battery_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/battery_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/battery_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/battery_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/bluerobin.obj: ../logic/bluerobin.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/bluerobin.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/bluerobin_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/bluerobin.pp" --obj_directory="logic" >> "logic/bluerobin_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/bluerobin_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/bluerobin_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/bluerobin_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/clock.obj: ../logic/clock.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/clock.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/clock_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/clock.pp" --obj_directory="logic" >> "logic/clock_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/clock_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/clock_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/clock_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/datalog.obj: ../logic/datalog.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/datalog.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/datalog_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/datalog.pp" --obj_directory="logic" >> "logic/datalog_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/datalog_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/datalog_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/datalog_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/date.obj: ../logic/date.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/date.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/date_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/date.pp" --obj_directory="logic" >> "logic/date_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/date_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/date_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/date_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/menu.obj: ../logic/menu.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/menu.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/menu_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/menu.pp" --obj_directory="logic" >> "logic/menu_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/menu_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/menu_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/menu_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/rfbsl.obj: ../logic/rfbsl.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/rfbsl.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/rfbsl_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/rfbsl.pp" --obj_directory="logic" >> "logic/rfbsl_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/rfbsl_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/rfbsl_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/rfbsl_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/rfsimpliciti.obj: ../logic/rfsimpliciti.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/rfsimpliciti.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/rfsimpliciti_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/rfsimpliciti.pp" --obj_directory="logic" >> "logic/rfsimpliciti_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/rfsimpliciti_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/rfsimpliciti_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/rfsimpliciti_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/temperature.obj: ../logic/temperature.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/temperature.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/temperature_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/temperature.pp" --obj_directory="logic" >> "logic/temperature_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/temperature_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/temperature_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/temperature_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

logic/user.obj: ../logic/user.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/user.pp" --obj_directory="logic"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_US --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "logic/user_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="logic/user.pp" --obj_directory="logic" >> "logic/user_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "logic/user_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "logic/user_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"logic/user_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '


