################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
simpliciti/Components/nwk_applications/nwk_freq.obj: ../simpliciti/Components/nwk_applications/nwk_freq.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_freq.pp" --obj_directory="simpliciti/Components/nwk_applications"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "simpliciti/Components/nwk_applications/nwk_freq_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_freq.pp" --obj_directory="simpliciti/Components/nwk_applications" >> "simpliciti/Components/nwk_applications/nwk_freq_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "simpliciti/Components/nwk_applications/nwk_freq_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "simpliciti/Components/nwk_applications/nwk_freq_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"simpliciti/Components/nwk_applications/nwk_freq_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

simpliciti/Components/nwk_applications/nwk_ioctl.obj: ../simpliciti/Components/nwk_applications/nwk_ioctl.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_ioctl.pp" --obj_directory="simpliciti/Components/nwk_applications"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "simpliciti/Components/nwk_applications/nwk_ioctl_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_ioctl.pp" --obj_directory="simpliciti/Components/nwk_applications" >> "simpliciti/Components/nwk_applications/nwk_ioctl_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "simpliciti/Components/nwk_applications/nwk_ioctl_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "simpliciti/Components/nwk_applications/nwk_ioctl_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"simpliciti/Components/nwk_applications/nwk_ioctl_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

simpliciti/Components/nwk_applications/nwk_join.obj: ../simpliciti/Components/nwk_applications/nwk_join.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_join.pp" --obj_directory="simpliciti/Components/nwk_applications"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "simpliciti/Components/nwk_applications/nwk_join_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_join.pp" --obj_directory="simpliciti/Components/nwk_applications" >> "simpliciti/Components/nwk_applications/nwk_join_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "simpliciti/Components/nwk_applications/nwk_join_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "simpliciti/Components/nwk_applications/nwk_join_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"simpliciti/Components/nwk_applications/nwk_join_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

simpliciti/Components/nwk_applications/nwk_link.obj: ../simpliciti/Components/nwk_applications/nwk_link.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_link.pp" --obj_directory="simpliciti/Components/nwk_applications"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "simpliciti/Components/nwk_applications/nwk_link_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_link.pp" --obj_directory="simpliciti/Components/nwk_applications" >> "simpliciti/Components/nwk_applications/nwk_link_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "simpliciti/Components/nwk_applications/nwk_link_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "simpliciti/Components/nwk_applications/nwk_link_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"simpliciti/Components/nwk_applications/nwk_link_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

simpliciti/Components/nwk_applications/nwk_mgmt.obj: ../simpliciti/Components/nwk_applications/nwk_mgmt.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_mgmt.pp" --obj_directory="simpliciti/Components/nwk_applications"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "simpliciti/Components/nwk_applications/nwk_mgmt_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_mgmt.pp" --obj_directory="simpliciti/Components/nwk_applications" >> "simpliciti/Components/nwk_applications/nwk_mgmt_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "simpliciti/Components/nwk_applications/nwk_mgmt_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "simpliciti/Components/nwk_applications/nwk_mgmt_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"simpliciti/Components/nwk_applications/nwk_mgmt_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

simpliciti/Components/nwk_applications/nwk_ping.obj: ../simpliciti/Components/nwk_applications/nwk_ping.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_ping.pp" --obj_directory="simpliciti/Components/nwk_applications"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "simpliciti/Components/nwk_applications/nwk_ping_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_ping.pp" --obj_directory="simpliciti/Components/nwk_applications" >> "simpliciti/Components/nwk_applications/nwk_ping_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "simpliciti/Components/nwk_applications/nwk_ping_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "simpliciti/Components/nwk_applications/nwk_ping_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"simpliciti/Components/nwk_applications/nwk_ping_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '

simpliciti/Components/nwk_applications/nwk_security.obj: ../simpliciti/Components/nwk_applications/nwk_security.c $(GEN_OPTS) $(GEN_SRCS)
	@echo 'Building file: $<'
	@echo 'Invoking: Compiler'
	@echo 'Flags: --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code"'
	@echo 'Flags (cont-d): --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_security.pp" --obj_directory="simpliciti/Components/nwk_applications"'
	$(shell echo --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\Vejed\Documents\workspace\ez430_chronos_datalogger\simpliciti\Applications\configuration\End Device\smpl_config.dat" -vmspx -g -O4 --opt_for_speed=0 --define=__CCE__ --define=ISM_LF --define=MRFI_CC430 --define=__CC430F6137__ --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/include" --include_path="C:/Program Files (x86)/TI/ccsv4/msp430/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/driver" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/include" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/logic" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/bluerobin" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Applications/application/End Device" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/boards/CC430EM/bsp_external" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/drivers/code" > "simpliciti/Components/nwk_applications/nwk_security_ccsCompiler.opt")
	$(shell echo --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/bsp/mcus" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/radios/family5" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/mrfi/smartrf" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk" --include_path="C:/Users/Vejed/Documents/workspace/ez430_chronos_datalogger/simpliciti/Components/nwk_applications" --diag_warning=225 --call_assumptions=0 --auto_inline=0 --gen_opt_info=2 --printf_support=minimal --preproc_with_compile --preproc_dependency="simpliciti/Components/nwk_applications/nwk_security.pp" --obj_directory="simpliciti/Components/nwk_applications" >> "simpliciti/Components/nwk_applications/nwk_security_ccsCompiler.opt")
	$(if $(strip $(GEN_OPTS_QUOTED)), $(shell echo $(GEN_OPTS_QUOTED) >> "simpliciti/Components/nwk_applications/nwk_security_ccsCompiler.opt"))
	$(if $(strip $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#")), $(shell echo $(subst #,$(wildcard $(subst $(SPACE),\$(SPACE),$<)),"#") >> "simpliciti/Components/nwk_applications/nwk_security_ccsCompiler.opt"))
	"C:/Program Files (x86)/TI/ccsv4/tools/compiler/msp430/bin/cl430" -@"simpliciti/Components/nwk_applications/nwk_security_ccsCompiler.opt"
	@echo 'Finished building: $<'
	@echo ' '


